using System.Collections.Generic;
using UnityEngine;

public static class CardDatabase
{
    public static List<Cards> cardList = new List<Cards>{
        new Cards(0, "None", 0, 0, 0, "None"),
        new Cards(1, "Maria Caninana", 1, 1, 2, "None"),
        new Cards(2, "Aticupu", 2, 1, 3, "Todo turno cura em 1 a carta escolhida até que morra."),
        new Cards(3, "Corpo Seco", 2, 1, 5, "Quando for derrotado, volta à mão do jogador."),
        new Cards(4, "Cumadre Fulôzinha", 2, 1, 2, "Envenena o alto do ataque por 2 turnos."),
        new Cards(5, "Hipocampo", 3, 2, 3, "Escolha um inimigo e reduza seu ataque em 1 por 2 turnos."),
        new Cards(6, "Boitatá", 3, 1, 6, "Reduz o dano de quem atacar por 1 turno."),
        new Cards(7, "Caipora", 3, 0, 3, "A cada turno dá 3 de escudo a uma carta aleatória aliada, priorizando outras cartas além de si mesma."),
        new Cards(8, "Curupira", 3, 3, 2, "Toda vez que atacar, ganha +1 de dano."),
        new Cards(9, "Matinta Pereira", 3, 1, 2, "Ao entrar em campo, dá duas cartas de consumível aleatórias."),
        new Cards(10, "Onça-boi", 3, 2, 3, "A cada onça boi aliada existente, adiciona +1 vida e dano às onça-boi existentes em campo."),
        new Cards(11, "Zumbi da meia noite", 3, 1, 5, "Só morre se perder toda sua vida numa única instância de dano."),
        new Cards(12, "Boiúna", 4, 2, 3, "Adiciona duas cartas de peixe à mão."),
        new Cards(13, "Alamoa - Humana", 4, 2, 6, "Escolha 2 inimigos e reduza sua vida em -1 ao seduzi-los. Upgrade: Se executar 2 inimigos, evolui."),
        new Cards(14, "Alamoa - Esqueleto", 4, 2, 8, "Ao atacar, se cura em 1."),
        new Cards(15, "Cobra Norato", 4, 1, 3, "Ao entrar em campo, escolhe uma carta aliada para conceder Sobrevida (revive com 1 de vida se for derrotada). Se esta carta for eliminada antes da ressurreição, o efeito desaparece."),
        new Cards(16, "Mula sem cabeça", 4, 2, 2, "Aplica queimadura por 3 turnos"),
        new Cards(17, "Negrinho do Pastoreio", 5, 2, 1, "Após ser derrotada, revive com 4 de vida e 4 de dano. Passivamente, recupera 1 de vida por turno."),
        new Cards(18, "Cuca", 5, 4, 4, "Rouba uma carta da mão do inimigo"),
        new Cards(19, "Barba ruiva - Criança", 5, 0, 8, "Se sobreviver por 3 rodadas, evolui. Upgrade: ganha +5 de dano e recupera toda a vida"),
        new Cards(20, "Barba ruiva - Adulto", 5, 5, 6, "None"),
        new Cards(21, "Boi Vaquim", 5, 4, 2, "Escolhe dois inimigos para que sejam atacados imediatamente ao ser jogado."),
        new Cards(22, "Iara", 5, 2, 4, "Condena o inimigo à sua frente à morte em três turnos. O efeito se dissipará se Iara morrer antes deste ser concretizado."),
        new Cards(23, "Lobisomem - Homem", 5, 2, 4, "Se sobreviver por 3 rounds, evolui ganhando +1 de dano e +2 de vida."),
        new Cards(24, "Lobisomem", 5, 3, 6, "Ao atacar cartas que não estão com a vida máxima, da +1 de dano."),
        new Cards(25, "Boto Cor de Rosa ", 6, 3, 3, "A cada 2 turnos, fica imune a danos. Causar 9 de dano faz com que evolua."),
        new Cards(26, "Boto Cor de Rosa - Homem", 6, 6, 4, "Reduz a vida máxima do inimigo atacado em 2."),
        new Cards(27, "Romãozinho", 6, 2, 2, "Reduz 1 de dano do inimigo à frente. Ao ver uma carta morrer ganha +1 de vida e +1 de dano. Ao morrer, perde seus incrementos e volta à mão."),
        new Cards(28, "Kianumaka Manã - Humana", 7, 3, 9, "Cura 1 de vida sempre que eliminar uma carta inimiga. Em campo: ao ver 3 cartas aliadas morrerem, evolui."),
        new Cards(29, "Kianumaka Manã - Onça", 7, 3, 9, "Ataca dois inimigos, um a sua frente e outro escolhido aleatoriamente."),
        new Cards(30, "Saci Pererê", 8, 4, 2, "Troca o dano pela vida das cartas inimigas em campo ao entrar na batalha. Atordoa uma carta alvo no campo."),
        new Cards(31, "Esqueleto", 1, 2, 1, "None"),
        new Cards(32, "Cobra", 1, 1, 2, "None"),
        new Cards(33, "Onça", 3, 2, 4, "None"),
        new Cards(34, "Lobo-guará", 3, 4, 2, "None"),
        new Cards(35, "Arara azul", 2, 2, 2, "None"),
        new Cards(36, "Sapo", 2, 3, 1, "None"),
        new Cards(37, "Gavião real", 4, 5, 2, "None"),
        new Cards(38, "Batata de purga", 3, 0, 0, "Remove todos os efeitos negativos (alvo-único) e cura em +1 de vida."),
        new Cards(39, "Guaraná", 6, 0, 0, "Escolha uma carta aliada para aumentar seu dano em metade do valor do dano dessa carta e permitir que ataque duas vezes no mesmo turno."),
        new Cards(40, "Inhame", 2, 0, 0, "Cura 1. O próximo dano recebido será reduzido em 1."),
        new Cards(41, "Ipecacuanha", 7, 0, 0, "Concede imunidade a efeitos negativos para todo o campo por 2 turnos."),
        new Cards(42, "Jerimum", 4, 0, 0, "Cura 1 para todas as cartas aliadas no campo."),
        new Cards(43, "Milho", 1, 0, 0, "Cura 1."),
        new Cards(44, "Vitória-régia", 3, 0, 0, "Cura 2."),
        new Cards(45, "Peixe", 1, 2, 1, "None"),
    };
}